name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Inject secrets into HTML
        env:
          GIST_TOKEN: ${{ secrets.DASASDASD }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          sed -i "s/const GITHUB_TOKEN = '';/const GITHUB_TOKEN = '${GIST_TOKEN}';/g" index.html
          sed -i "s/const ADMIN_PASSWORD = 'your-secure-password';/const ADMIN_PASSWORD = '${ADMIN_PASS}';/g" index.html
          sed -i "s|const DISCORD_WEBHOOK = '';|const DISCORD_WEBHOOK = '${WEBHOOK_URL}';|g" index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
