name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Inject secrets
        env:
          GIST_TOKEN: ${{ secrets.DASASDASD }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python .github/scripts/inject_secrets.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
